### ISSUE TITLE
How to extend the current range

### ISSUE THREAD

**Issue by marcossouza12** [KyleLopin/Potentiostat_GUI#1]
Hi KyleLopin,
I have tried to extend the current range using an external resistor (100 Ohm) between P[0][4] and P[0][7]. However, I don't know to active this setting in the GUI.  I tried to do this in Options>Add custom TIA resistor, but when I enter the resistor value and channel it is connected then powershell shows the following error mensage:
Traceback (most recent call last):
    File "tkinter\__init__.py", line 1705, in __call__
    File "change_toplevel.py", line 863, in <lambda>
    File "change_toplevel.py", line 879, in save
TypeError: set_value() missing 3 required positional arguments: 'new_adc_gain_value', 'new_adc_config', and 'current_range_index'

I will be very grateful if you can help me!

**Comment by ghost** [comment]
s that possible to drive or identify the issue related to DPV-based GUI not opening & Someone identified as well (Azkaban)? Shall we focus on that? Is that 2020 HEX file compatible with the 2020-based GUI? What is the opinion???? Can we increase the number of CV Cycles for the GUI?? Please let me know.

**Comment by ghost** [comment]
> Hi KyleLopin, I have tried to extend the current range using an external resistor (100 Ohm) between P[0][4] and P[0][7]. However, I don't know to active this setting in the GUI. I tried to do this in Options>Add custom TIA resistor, but when I enter the resistor value and channel it is connected then powershell shows the following error mensage: Traceback (most recent call last): File "tkinter__init__.py", line 1705, in **call** File "change_toplevel.py", line 863, in File "change_toplevel.py", line 879, in save TypeError: set_value() missing 3 required positional arguments: 'new_adc_gain_value', 'new_adc_config', and 'current_range_index'
> 
> I will be very grateful if you can help me!

I am having all code with me (https://drive.google.com/drive/folders/1hKyy2O2HLyh9o4wxKsPFoyXOMyaorkv7)

https://www.duo.uio.no/bitstream/handle/10852/82665/5/Olav-Bjerke---masteroppgave.pdf .

Getting USB Time out error while replicating this into CY8CKIT-059
